[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "kitchen-agent"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "anthropic",
    "beautifulsoup4",
    "fastapi",
    "httpx",
    "mangum",
    "numpy",
    "optimum[onnxruntime]",
    "Pillow",
    "psycopg2-binary",
    "python-dotenv",
    "python-multipart",
    "requests",
    "sentence-transformers",
    "uvicorn",
    "yt-dlp",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-dir]
"" = "src"
